version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/data

  server:
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - ./server:/data

